apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdata-depl
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: userdata
  template:
    metadata:
      labels:
        app: userdata
    spec:
      containers:
        - name: userdata
          image: digicel/userdata:latest
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: userdata-srv
spec:
  selector: 
    app: userdata
  ports:
    - name: userdata
      protocol: TCP
      port: 3000
      targetPort: 3000